[package]
name    = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
core-lib = { path = "../core-lib" }
common   = { path = "../common" }

tokio              = { workspace = true }
clap               = { version = "4.5.37", features = ["derive"] }
tracing            = "0.1.41"
tracing-subscriber = "0.3.19"
