name: CI (Linux)

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        name: Test (${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.rust }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      arch: x86_64
                      rust: stable
                    - os: ubuntu-latest-arm64
                      arch: aarch64
                      rust: stable
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@v1
              with:
                  toolchain: ${{ matrix.rust }}
            - uses: Swatinem/rust-cache@v2
            - name: Test
              run: cargo test --workspace --all-targets --all-features

    coverage:
        name: Coverage (${{ matrix.os }} ${{ matrix.arch }})
        runs-on: ${{ matrix.os }}
        needs: test
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      arch: x86_64
                      rust: nightly
                    - os: ubuntu-latest-arm64
                      arch: aarch64
                      rust: nightly
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@v1
              with:
                  toolchain: nightly
            - uses: Swatinem/rust-cache@v2
            - name: Install grcov
              run: cargo install grcov
            - name: Run tests with coverage
              run: |
                  export CARGO_INCREMENTAL=0
                  export RUSTFLAGS="-Zinstrument-coverage"
                  export LLVM_PROFILE_FILE="gboxide-%p-%m.profraw"
                  cargo test --workspace --all-targets --all-features
            - name: Generate coverage report
              run: |
                  grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o lcov.info
            - name: Upload coverage artifact
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-lcov
                  path: lcov.info
