name: CI (Windows)

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        name: Test (windows-latest x86_64 ${{ matrix.rust }})
        runs-on: windows-latest
        strategy:
            matrix:
                rust: [stable, beta, nightly]
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@v1
              with:
                  toolchain: ${{ matrix.rust }}
            - uses: Swatinem/rust-cache@v2
            - name: Test
              run: cargo test --all-features --all-targets --locked
            - name: Clippy
              run: cargo clippy --all-targets --all-features
            - name: Fmt
              run: cargo fmt -- --check

    coverage:
        name: Coverage (windows-latest x86_64)
        runs-on: windows-latest
        needs: test
        strategy:
            matrix:
                rust: [nightly]
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@v1
              with:
                  toolchain: nightly
            - uses: Swatinem/rust-cache@v2
            - name: Install cargo-llvm-cov
              run: cargo install cargo-llvm-cov
            - name: Run coverage
              run: cargo llvm-cov --all-features --lcov --output-path lcov.info
            - name: Upload coverage artifact
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-lcov
                  path: lcov.info

    msrv:
        name: MSRV Check (cargo-msrv)
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@v1
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@v2
            - name: Install cargo-msrv
              run: cargo install cargo-msrv
            - name: Find and check MSRV
              run: cargo msrv verify --output-format json
