name: CI (wasm32-unknown-unknown)

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    check-wasm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@v1
              with:
                  toolchain: stable
                  targets: wasm32-unknown-unknown
            - uses: Swatinem/rust-cache@v2
            - name: Check (wasm32-unknown-unknown)
              run: cargo check --target wasm32-unknown-unknown --all-features --locked
            - name: Clippy (wasm32-unknown-unknown)
              run: cargo clippy --target wasm32-unknown-unknown --all-features
            - name: Fmt
              run: cargo fmt -- --check
            # Optional: If you use wasm-bindgen-test or similar for wasm tests
            # - name: Install wasm-bindgen-test
            #   run: cargo install wasm-bindgen-test-runner
            # - name: Test (wasm32-unknown-unknown)
            #   run: cargo test --target wasm32-unknown-unknown
